### ISSUE TITLE
Jobs stuck in restriction_ queue

### ISSUE THREAD

**Issue by thatdom** [flyerhzm/resque-restriction#10]
I created a simple job, all it does is:
    puts "START #{id}"
    sleep 2.5
    puts "END #{id}"

My restriction is 2 jobs per second:  restrict :per_1 => 2

Then I run pool of 10 workers and queued 10 jobs with:
1.upto(10) do |i|
  Resque.enqueue(InstagramFeed,i)
end

2 Jobs start and finish executing, other 8 jobs are moved to "restriction_instagram" queue and never executed.

Not sure what's wrong.

**Comment by mfo** [comment]
What's your version of resque-restriction ?

**Comment by thatdom** [comment]
0.3.0

**Comment by tmedford** [comment]
I can confirm on 0.3.0. Gem restricts but the restricted never seem to get run.

**Comment by mfo** [comment]
FYI : it's under investigation. Currently it works with 0.4.2 ; are you sure you have a resque worker with a QUEUE=* ? [I'm asking just in case no worker could fetch your job ]

**Comment by flyerhzm** [comment]
I tried today and it's working well.
