### ISSUE TITLE
Can't Install Gem File, GemSpec Wrong

### ISSUE THREAD

**Issue by tmedford** [flyerhzm/resque-restriction#12]
gem install resque-restriction
Fetching: resque-restriction-0.4.0.gem (100%)
ERROR:  Error installing resque-restriction:
	resque-restriction requires resque-restriction (>= 0)

**Comment by mfo** [comment]
Hi ;

Just released 0.4.2 ( 0.4.1 had been yanked [my first time with releasing gems] ) ; thanks for your feedback
