### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by justinvj15** [flyerhzm/resque-restriction#5]
This doesn't seem to be working for me.I have installed this gem correctly.Readme says "Resque Restriction requires Resque 1.7.0." but i think the current version of resque gem is 1.17.1.

  class FetchSources < Resque::Plugins::RestrictionJob
    restrict :per_day => 100, :per_hour => 10, :per_minute => 3
    queue = :fetch_sources
    #rest of the stuff
  end 
    This is my code.i can't see any restriction are get applied on fetch_sources queue when i run it.

Thanks.

**Comment by mfo** [comment]
outdated
