### ISSUE TITLE
Help testing against edge resque

### ISSUE THREAD

**Issue by steveklabnik** [flyerhzm/resque-restriction#7]
Hey there! 

I'm gearing up to work on Resque 2.0, and I'd like to coordinate better with plugin authors to make sure stuff doesn't break.

I'd like to know a few things:

1. Can I do something to help get you testing against edge Resque?
2. Are you monkey-patching anything in Resque currently? Can 2.0 expose an API to help you not have to do that any more?
3. Do you need any help in bringing your plugin up-to-date with the latest Resque?

Thanks!

Related: https://github.com/defunkt/resque/issues/880

**Comment by mfo** [comment]
Hi Steve, 
just pushed a compatible version of resque-restriction with ActiveJob, while I'm updating my tech stack, do you have any idea when resque 2 will be released? Maybe I'll be able to update both gems together and provide you interesting feedbacks

BEst

**Comment by steveklabnik** [comment]
Hey @mfo !

I'm not working on Resque anymore, so I don't know if and when 2.0 will ever be relased. :(

**Comment by mfo** [comment]
K sry for the outdated reply :/

**Comment by mfo** [comment]
Outdated since resque 2.0 is stuck. I'll re-open if it's released one day
